/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Donor = IDL.Record({
  'id' : IDL.Principal,
  'age' : IDL.Nat,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'lastDonationDate' : Time,
  'bloodGroup' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BloodStock = IDL.Record({
  'bloodGroup' : IDL.Text,
  'unitsAvailable' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'timeCreated' : Time,
});
export const Request = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'bloodGroup' : IDL.Text,
  'units' : IDL.Nat,
  'requestDate' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDonor' : IDL.Func([Donor], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countRequestsByStatus' : IDL.Func(
      [
        IDL.Variant({
          'pending' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
      ],
      [IDL.Nat],
      ['query'],
    ),
  'createRequest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllBloodStock' : IDL.Func([], [IDL.Vec(BloodStock)], ['query']),
  'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
  'getBloodStock' : IDL.Func([IDL.Text], [IDL.Opt(BloodStock)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonor' : IDL.Func([IDL.Principal], [IDL.Opt(Donor)], ['query']),
  'getRequestsByStatus' : IDL.Func(
      [
        IDL.Variant({
          'pending' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
      ],
      [IDL.Vec(Request)],
      ['query'],
    ),
  'getRequestsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Request)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerProfile' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBloodStock' : IDL.Func([BloodStock], [], []),
  'updateRequestStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Donor = IDL.Record({
    'id' : IDL.Principal,
    'age' : IDL.Nat,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'lastDonationDate' : Time,
    'bloodGroup' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BloodStock = IDL.Record({
    'bloodGroup' : IDL.Text,
    'unitsAvailable' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'timeCreated' : Time,
  });
  const Request = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'bloodGroup' : IDL.Text,
    'units' : IDL.Nat,
    'requestDate' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDonor' : IDL.Func([Donor], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countRequestsByStatus' : IDL.Func(
        [
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
        ],
        [IDL.Nat],
        ['query'],
      ),
    'createRequest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllBloodStock' : IDL.Func([], [IDL.Vec(BloodStock)], ['query']),
    'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
    'getBloodStock' : IDL.Func([IDL.Text], [IDL.Opt(BloodStock)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonor' : IDL.Func([IDL.Principal], [IDL.Opt(Donor)], ['query']),
    'getRequestsByStatus' : IDL.Func(
        [
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
        ],
        [IDL.Vec(Request)],
        ['query'],
      ),
    'getRequestsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Request)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerProfile' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBloodStock' : IDL.Func([BloodStock], [], []),
    'updateRequestStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };