/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BloodStock { 'bloodGroup' : string, 'unitsAvailable' : bigint }
export interface Donor {
  'id' : Principal,
  'age' : bigint,
  'contact' : string,
  'name' : string,
  'lastDonationDate' : Time,
  'bloodGroup' : string,
}
export interface Request {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'user' : Principal,
  'bloodGroup' : string,
  'units' : bigint,
  'requestDate' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'email' : [] | [string],
  'timeCreated' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDonor' : ActorMethod<[Donor], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countRequestsByStatus' : ActorMethod<
    [{ 'pending' : null } | { 'approved' : null } | { 'rejected' : null }],
    bigint
  >,
  'createRequest' : ActorMethod<[string, bigint], undefined>,
  'getAllBloodStock' : ActorMethod<[], Array<BloodStock>>,
  'getAllDonors' : ActorMethod<[], Array<Donor>>,
  'getBloodStock' : ActorMethod<[string], [] | [BloodStock]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonor' : ActorMethod<[Principal], [] | [Donor]>,
  'getRequestsByStatus' : ActorMethod<
    [{ 'pending' : null } | { 'approved' : null } | { 'rejected' : null }],
    Array<Request>
  >,
  'getRequestsByUser' : ActorMethod<[Principal], Array<Request>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerProfile' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBloodStock' : ActorMethod<[BloodStock], undefined>,
  'updateRequestStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'approved' : null } |
        { 'rejected' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];